### ISSUE TITLE
Add support for Amazon Music? 

### ISSUE THREAD

**Issue by chromaniac2** [Vivalldi/NowPlayingHistory#3]
Not sure if this is something you can do. Right now selecting Amazon Music does not load the song in the app. It just loads the app to the screen where it was left.

**Comment by Vivalldi** [comment]
@Sushubh I can take a look as to why it does that. It may be something with Amazon Music however as essentially all the app does is send a "broadcast" saying "Hey, I've got this song. Anyone want to play it?" and then the apps that show up in the list are ones that think, "Oh yeah, I can play that." It's a bit iffy but I'll see if I can transform it

**Comment by chromaniac2** [comment]
Right. Can you suggest any other app using which I can send a similar broadcast to Amazon Music to see if it responds to that? Shazam does not list Amazon Music at my end. Google Assistant music search does not list Amazon Music. 

Update. Ok I just used a voice command to play something using Amazon Music. It showed the same behavior. Opened Amazon Music but nothing really played. So I am guessing this is an issue at Amazon's end. The app seems to be designed to just accept commands using Alexa and no other route. 

Is there anything specific terminology that you can recommend that I can possibly send as a bug report (if they have one) or a command on their Google Store listing or send as email through support channels.

**Comment by Vivalldi** [comment]
Thanks for doing some basic testing. I would say something along the lines of,

> While working with various other apps I noticed that Amazon Music does not respond to "Intents" the same way that other apps do. The intent in question is "INTENT_ACTION_MEDIA_PLAY_FROM_SEARCH" which is supposed to create a search and play the first result. 

Best of luck and if you have any other questions feel free to ask (going to close this for now)
